dyoshikawa/rulesync

package.json, src/cli/index.ts
Release version 0.43.0
- Updated version in src/cli/index.ts
- Updated version in package.json
This PR contains the version bump for the v0.43.0 release.
=> release: version 0.43.0

.gitignore, src/cli/commands/add.test.ts, src/cli/commands/generate.test.ts, src/cli/commands/status.test.ts, src/cli/commands/validate.test.ts, src/cli/commands/watch.test.ts, src/core/generator.test.ts, src/core/importer.test.ts, src/core/importer.ts, src/core/parser.test.ts, src/generators/rules/cline.test.ts, src/generators/rules/copilot.test.ts, src/generators/rules/cursor.test.ts, src/generators/rules/geminicli.test.ts, src/generators/rules/kiro.test.ts, src/generators/rules/roo.test.ts, src/parsers/cursor.test.ts, src/test-utils/mock-config.ts
- Changed  → 
- Improved naming that is more intuitive and clearly indicates purpose
- Updated JSDoc comments appropriately
- Added  pattern to 
- Prevents temporary directories created during test execution from being tracked by Git
- Removed existing  directory
-  - Function definition updates
- 6 test files - Import and call updates
-  - Test temporary directory exclusion settings
- ✅ Improved test code readability
- ✅ Better future maintainability
- ✅ Improved temporary file management during test execution
- ✅ Confirmed all tests are working correctly
=> refactor: rename createMinimalMockConfig to createMockConfigByTool and add test directory ignore

package.json, src/cli/index.ts
Release version 0.46.0
- Update version to 0.46.0 in src/cli/index.ts
- Update package.json version to 0.46.0
=> Release v0.46.0

package.json, src/cli/index.ts
Release v0.49.0
AugmentCode対応追加がメインのリリースです。
=> release: v0.49.0

package.json, src/cli/index.ts
=> release: v0.52.0

package.json, src/cli/index.ts
Version bump to v0.54.0
This PR contains the version updates for the v0.54.0 release.
=> Release v0.54.0

package.json, src/cli/index.ts
=> Release v0.60.0

package.json, src/cli/index.ts
=> chore: release v0.65.0

package.json, src/cli/index.ts
Release v0.68.1
This patch release includes:
- Improve processor load handling and error management (#220)
This version bump updates the CLI fallback version and package.json to v0.68.1.
=> Release v0.68.1

package.json, src/cli/index.ts
Release preparation for v0.69.0
- Update fallback version to 0.69.0
- Bump package.json version to 0.69.0
- Add Warp tool support to rulesync
This release adds support for generating Warp terminal configuration files from rulesync AI rules.
=> Release v0.69.0

package.json, src/cli/index.ts
This PR contains the version bump for release v0.70.0.
- Update fallback version in CLI to 0.70.0
- Bump package.json version to 0.70.0
The release includes features, refactoring, documentation improvements, and various chores. Full release notes will be published with the GitHub release.
=> Release v0.70.0

package.json, src/cli/index.ts
- Update version to 0.80.0 in CLI
- Bump package.json version to 0.80.0
* fix: remove invalid Dependabot configuration properties (#272)
* fix: update Dependabot auto-merge workflow with correct repository
* feat: add Dependabot configuration with auto-merge support
* ci(deps): bump actions/checkout from 4 to 5 (#273)
* ci(deps): bump pnpm/action-setup from 2 to 4 (#275)
* chore: streamline CI/CD workflows and release process (#276)
* chore(dependabot): reduce open-pull-requests-limit for better manageability and add new group for all actions to streamline updates (#277)
* chore: update Dependabot auto-merge workflow configuration
* docs: update capitalization of "rulesync" to "Rulesync" for consistency across documentation (#269)
* chore(tests): remove logger test file as it is no longer …
=> Release v0.80.0

src/cli/index.ts
- https://github.com/dyoshikawa/rulesync/pull/305
- https://github.com/Homebrew/homebrew-core/pull/245167
=> fix: update fallback version to 1.2.1

src/cli/index.ts
- https://github.com/Homebrew/homebrew-core/pull/245661
=> fix: Bump version from 1.2.5 to 1.2.6

package.json, src/cli/index.ts
Release version 2.0.0
- Update version to 2.0.0 in getVersion()
- Bump package.json version to 2.0.0
This PR is part of the release process for v2.0.0.
=> Release v2.0.0

package.json, src/cli/index.ts
=> chore: release v2.0.1

package.json, src/cli/index.ts
=> chore: release v3.1.0

package.json, src/cli/index.ts
=> Release v3.2.0

package.json, src/cli/index.ts
=> chore: release v3.3.1

package.json, src/cli/index.ts
This PR updates the version to 3.4.0.
- Update getVersion() to return 3.4.0
- Update package.json version to 3.4.0
See release notes in ai-tmp/release-notes.md for details.
=> Release v3.4.0
